<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SLB-F2NLRF2" failures="1" tests="9" name="com.restapi_TestCases.TC005_Delete_EmployeeRecord" time="0.011" errors="0" timestamp="2020-06-15T09:34:44 IST" skipped="0">
  <testcase classname="com.restapi_TestCases.TC005_Delete_EmployeeRecord" name="checkContentEncodeType" time="0.002"/>
  <system-out/>
  <testcase classname="com.restapi_TestCases.TC005_Delete_EmployeeRecord" name="checkReponseTime" time="0.002"/>
  <system-out/>
  <testcase classname="com.restapi_TestCases.TC005_Delete_EmployeeRecord" name="checkServerType" time="0.001"/>
  <system-out/>
  <testcase classname="com.restapi_TestCases.TC005_Delete_EmployeeRecord" name="checkCookies" time="0.000"/>
  <system-out/>
  <testcase classname="com.restapi_TestCases.TC005_Delete_EmployeeRecord" name="checkContentLength" time="0.002"/>
  <system-out/>
  <testcase classname="com.restapi_TestCases.TC005_Delete_EmployeeRecord" name="checkStatusLine" time="0.001"/>
  <system-out/>
  <testcase classname="com.restapi_TestCases.TC005_Delete_EmployeeRecord" name="checkStatusCode" time="0.001"/>
  <system-out/>
  <testcase classname="com.restapi_TestCases.TC005_Delete_EmployeeRecord" name="checkTheContentType" time="0.001"/>
  <system-out/>
  <testcase classname="com.restapi_TestCases.TC005_Delete_EmployeeRecord" name="checkResponseBody" time="0.001">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:751)
at org.testng.Assert.assertEquals(Assert.java:761)
at com.restapi_TestCases.TC005_Delete_EmployeeRecord.checkResponseBody(TC005_Delete_EmployeeRecord.java:49)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- checkResponseBody -->
  <system-out/>
</testsuite> <!-- com.restapi_TestCases.TC005_Delete_EmployeeRecord -->
